// ignore_for_file: unnecessary_string_escapes

Map<String, dynamic> bdfood = <String, dynamic>{
  "bread": [
    {
      "id": "01",
      "title": "No Dough Paratha Recipe | Bella Chara Porota",
      "image": "assets/images/bread/1.jpg",
      "ingredients": [
        "1 cup Wheat flour",
        "1 tbsp Milk powder",
        "1/2 tsp Sugar",
        "To taste Salt",
        "To fry Oil",
      ],
      "directions": [
        "In a bowl take all purpose flour, sugar, salt and milk powder. Add water gradually and make a smooth batter. Whisk the batter for 2-3 minutes till smooth. Cover and rest for 5 minutes.",
        "Heat a pan and brush oil all over the pan. Then turn flame into low and pour a spoonful of batter in the pan. Spread like a round shape roti. Then allow it to cook one side.",
        "When done, flip it and cook another side. Add 1 tsp of oil and cook both sides till brown in color. Then take out of the pan and keep on a tissue paper to absorb excess oil. Then serve.",
      ],
      "youtubeUrl": "https://youtu.be/WZuBGXtcXzU",
    },
    {
      "id": "02",
      "title": "Restaurant Style Garlic Bread Recipe",
      "image": "assets/images/bread/2.jpg",
      "ingredients": [
        "1 cup Wheat flour",
        "1 tsp Dry yeast",
        "As required Warm milk or water",
        "2 tbsp Oil",
        "1 tsp Sugar",
        "To taste Salt",
        "1 tbsp Butter",
        "1 tbsp Chopped garlic",
        "2 tbsp Coriander leaves",
        "As required Grated cheese",
        "As required Chili flakes",
        "As required Italian mixed herb",
      ],
      "directions": [
        "Take a large bowl. Add flour, sugar, salt and yeast. Mix all dry ingredients. Then gradually add lukewarm liquid milk and make a soft dough. Add oil and again knead the dough for 2 to 3 minutes. Cover and leave it for 2 hours to activate yeast.",
        "Now in small mixing bowl add butter, chopped garlic & coriander leaves and mix. Then spread half of this mixture on the half of the bread. Add grated cheese and sprinkle chili flakes and oregano-parsley. Fold into half and spread remaining butter mix and sprinkle chili flakes & oregano-parsley on the top.",
        "Preheat oven with 160 degree centigrade for 10 minutes. Bake for 15-20 minutes. When it is perfectly done, take out of the oven. Cool down a bit, cut into pieces and serve warm.",
      ],
      "youtubeUrl": "https://youtu.be/xDYfL_HIjhk",
    },
    {
      "id": "03",
      "title": "Palm Cake | Taler Pua/Malpua/Teler Pitha",
      "image": "assets/images/bread/3.jpg",
      "ingredients": [
        "1 cup Palm pulp",
        "2 cups Rice flour",
        "1/2 cup All purpose flour",
        "3/4 cup Sugar",
        "To taste Salt",
        "For deep fry Oil",
      ],
      "directions": [
        "In a bowl add palm pulp, rice flour, all purpose flour, sugar, salt and milk. Add water gradually and make a smooth batter. Whisk the batter for 2-3 minutes till smooth. Cover and rest for 30 minutes.",
        "After 30 minutes whisk the batter again with your hands or whisk for 5 minutes.",
        "Heat oil in a pan for deep fry. At first heat oil on medium flame. Then turn flame into low and pour a spoonful of batter in the oil. Then allow it to rise and puff up. You can tap oil by a spoon or spatula on the top to rise up. Then fry both sides till brown and perfectly cooked.",
        "When done, take out of the oil by a strainer and keep on a tissue paper to absorb excess oil. Then serve.",
      ],
      "youtubeUrl": "https://youtu.be/8XCiUiCe2uU",
    },
    {
      "id": "04",
      "title": "Malai Cake Recipe Bangla",
      "image": "assets/images/bread/4.jpg",
      "ingredients": [
        "1 cup Wheat flour",
        "3 pcs Eggs",
        "1/2 cup for cake, 1/4 cup for malai Sugar",
        "1/3 cup Oil",
        "1 tsp Baking powder",
        "2 tbsp Powder milk",
        "3 cups Liquid milk",
        "1/4 tsp Cardamom powder",
        "As required Chopped dried nuts & fruits",
      ],
      "directions": [
        "First of all mix all dry ingredients together and strain with a strainer. Keep aside.",
        "Take normal temperature eggs in a large bowl. If they were in fridge, keep them out of the fridge at least one hour ago. Carefully separate egg yolks and keep it aside. Now beat egg whites with a hand beater or hand whisk. When it turns into foam, gradually add icing sugar/sugar and beat well. After that gradually add egg yolks and oil or melted butter and beat again.",
        "Now add the mixture of dry ingredients. Gradually add them and mix with a spatula or spoon. Do not over-mix or do not use hand beater in this stage.",
        "Grease a cake mold with oil or butter placing a parchment paper or normal paper at bottom. Pour cake mix/batter in it. Tap few times to remove bubbles.",
        "Preheat your oven for 10 minutes. Then bake your cake in 160°C for 20 minutes. After 20 minutes check with a toothpick. If toothpick comes out clean the cake is ready. If not bake for 5 minutes more.",
        "Now take 3 cups of liquid milk, sugar, cardamom powder and bring it to boil. Reduce 3 cups of milk into 2 cups. Let it be cool a bit. Then pour it on the top of the cake. You can sprinkle some dried fruits & nuts on the top optionally. Keep it in the fridge. Let it completely be cool down. Then serve.",
      ],
      "youtubeUrl": "https://youtu.be/nZElRlcTSx0",
    },
    {
      "id": "05",
      "title": "Pizza Recipe without Oven",
      "image": "assets/images/bread/5.jpg",
      "ingredients": [
        "1 cup Flour",
        "1 tsp Sugar",
        "1 tsp Instant dry yeast",
        "2 tbsp Oil",
        "To taste Tomato sauce/pizza sauce",
        "As required Grated cheese",
        "As required Capsicum",
        "As required Chopped onion",
        "As required Sausage",
        "As required Mixed herbs",
        "As required Chili flakes",
        "To taste Salt",
      ],
      "directions": [
        "Take a large bowl. Add flour, sugar, salt and yeast. Mix all dry ingredients. Then gradually add lukewarm liquid milk and make a soft dough. Add oil and again knead the dough for 2 to 3 minutes. Cover and leave it for 2 hours to activate yeast.",
        "After two hours the dough will get double in size. Knead the dough again. Stretch and fold into inside with your hands. Now place it on the fry pan and flatten with your hands till your desired size with common pizza shape.",
        "Make some holes with a fork on the surface to avoid unnecessary bubbles. Cover and bake on very low flame one side for 5 minutes. Then bake another side for another 5 minutes. Now flip it and add tomato sauce, cheese, sausage, onion, capsicum or any of your favorite toppings.",
        "Cover it and cook till everything is well cooked and cheeses are melted. Then cut into pieces and serve warm.",
      ],
      "youtubeUrl": "https://youtu.be/2KpaxEHPNPk",
    },
    {
      "id": "06",
      "title": "Mini Moglai Porota Recipe | Mughlai Paratha",
      "image": "assets/images/bread/6.jpg",
      "ingredients": [
        "1 cup Wheat flour",
        "1 pc Egg",
        "1/2 cup Chopped onion",
        "1 tsp Chopped green chili",
        "1 tbsp Coriander leaves",
        "1/2 tsp Roasted cumin powder",
        "To deep fry Oil",
        "To taste Salt",
      ],
      "directions": [
        "In a bowl take flour, salt and 1 tsp oil. Mix them nicely with your hand. Add water gradually and make a soft dough. Knead the dough for 2-3 minutes till smooth. Grease some oil over the dough, cover and rest for 30 minutes.",
        "Meanwhile prepare egg staffing. In a bowl take green chilies, chopped onion, coriander leaves, cumin powder, salt & egg and mix everything well. Keep it aside.",
        "Now take the dough and cut into 6 equal pieces. Take all pieces and give them ball-shape by hand one by one. Take a ball and flatten as thin as possible. Place some egg stuffing in middle and close it by stretching the edges towards the center like paratha.",
        "Heat oil in a pan for deep fry. Add mini parathas carefully in it and fry one side till brown. Then flip it and fry both sides till brown on medium-low flame. Then take them out, leave them on a tissue paper to absorb excess oil and serve warm with chopped cucumber, onion and/or ketchup or sauce.",
      ],
      "youtubeUrl": "https://youtu.be/nzE-6OplwEU",
    },
    {
      "id": "07",
      "title": "Super Easy Vanilla Cake Recipe",
      "image": "assets/images/bread/7.jpg",
      "ingredients": [
        "1/2 cup All purpose flour",
        "1 tsp Baking powder",
        "2 pcs Egg",
        "1/2 cup Sugar",
        "1/4 cup Oil/ butter",
        "1 tsp Vanilla essence",
      ],
      "directions": [
        "Firstly mix all dry ingredients together and strain with a strainer.",
        "In a blender jug take eggs of normal temperature, sugar, oil and vanilla essence. Blend very well for 2-4 minutes or till sugar melt. When they turn into bubbly and fluffy mixture stop blending.",
        "In a large bowl take all dry ingredients and mix well. Then gradually add egg mixture and mix with a spatula or whisk very patiently. Do not overmix.",
        "Grease a cake mold with oil or butter. Place a baking paper at bottom. Pour cake mix/batter in it and tap few times to remove bubbles.",
        "Preheat a pan with lid for 5 minutes. Then place a stand and keep cake mold in it. Bake on very low flame for 40-45 minutes with the lid. If you want to bake in oven preheat your oven for 10 minutes. Then bake your cake in 160°C for 30-35 minutes.",
        "After 45 minutes check with a toothpick. If toothpick comes out clean the cake is ready to serve. If not bake for 5 minutes more. Follow the same process for oven also. Then take the mold out and keep to let it cool down completely. De-mold with a knife or spoon. Cut into pieces of your favorite size and serve.",
      ],
      "youtubeUrl": "https://youtu.be/wE1AFd5Xm9c",
    },
  ],
  "rice": [
    {
      "id": "01",
      "title": "No Dough Paratha Recipe | Bella Chara Porota",
      "image": "assets/images/rice/1.jpg",
      "ingredients": [
        "1 cup Wheat flour",
        "1 tbsp Milk powder",
        "1/2 tsp Sugar",
        "To taste Salt",
        "To fry Oil",
      ],
      "directions": [
        "In a bowl take all purpose flour, sugar, salt and milk powder. Add water gradually and make a smooth batter. Whisk the batter for 2-3 minutes till smooth. Cover and rest for 5 minutes.",
        "Heat a pan and brush oil all over the pan. Then turn flame into low and pour a spoonful of batter in the pan. Spread like a round shape roti. Then allow it to cook one side.",
        "When done, flip it and cook another side. Add 1 tsp of oil and cook both sides till brown in color. Then take out of the pan and keep on a tissue paper to absorb excess oil. Then serve.",
      ],
      "youtubeUrl": "https://youtu.be/WZuBGXtcXzU",
    },
    {
      "id": "02",
      "title": "Restaurant Style Garlic Bread Recipe",
      "image": "assets/images/rice/2.jpg",
      "ingredients": [
        "1 cup Wheat flour",
        "1 tsp Dry yeast",
        "As required Warm milk or water",
        "2 tbsp Oil",
        "1 tsp Sugar",
        "To taste Salt",
        "1 tbsp Butter",
        "1 tbsp Chopped garlic",
        "2 tbsp Coriander leaves",
        "As required Grated cheese",
        "As required Chili flakes",
        "As required Italian mixed herb",
      ],
      "directions": [
        "Take a large bowl. Add flour, sugar, salt and yeast. Mix all dry ingredients. Then gradually add lukewarm liquid milk and make a soft dough. Add oil and again knead the dough for 2 to 3 minutes. Cover and leave it for 2 hours to activate yeast.",
        "Now in small mixing bowl add butter, chopped garlic & coriander leaves and mix. Then spread half of this mixture on the half of the bread. Add grated cheese and sprinkle chili flakes and oregano-parsley. Fold into half and spread remaining butter mix and sprinkle chili flakes & oregano-parsley on the top.",
        "Preheat oven with 160 degree centigrade for 10 minutes. Bake for 15-20 minutes. When it is perfectly done, take out of the oven. Cool down a bit, cut into pieces and serve warm.",
      ],
      "youtubeUrl": "https://youtu.be/xDYfL_HIjhk",
    },
    {
      "id": "03",
      "title": "Palm Cake | Taler Pua/Malpua/Teler Pitha",
      "image": "assets/images/rice/3.jpg",
      "ingredients": [
        "1 cup Palm pulp",
        "2 cups Rice flour",
        "1/2 cup All purpose flour",
        "3/4 cup Sugar",
        "To taste Salt",
        "For deep fry Oil",
      ],
      "directions": [
        "In a bowl add palm pulp, rice flour, all purpose flour, sugar, salt and milk. Add water gradually and make a smooth batter. Whisk the batter for 2-3 minutes till smooth. Cover and rest for 30 minutes.",
        "After 30 minutes whisk the batter again with your hands or whisk for 5 minutes.",
        "Heat oil in a pan for deep fry. At first heat oil on medium flame. Then turn flame into low and pour a spoonful of batter in the oil. Then allow it to rise and puff up. You can tap oil by a spoon or spatula on the top to rise up. Then fry both sides till brown and perfectly cooked.",
        "When done, take out of the oil by a strainer and keep on a tissue paper to absorb excess oil. Then serve.",
      ],
      "youtubeUrl": "https://youtu.be/8XCiUiCe2uU",
    },
  ],
  "dessert": [
    {
      "id": "01",
      "title": "No Dough Paratha Recipe | Bella Chara Porota",
      "image": "assets/images/dessert/1.jpg",
      "ingredients": [
        "1 cup Wheat flour",
        "1 tbsp Milk powder",
        "1/2 tsp Sugar",
        "To taste Salt",
        "To fry Oil",
      ],
      "directions": [
        "In a bowl take all purpose flour, sugar, salt and milk powder. Add water gradually and make a smooth batter. Whisk the batter for 2-3 minutes till smooth. Cover and rest for 5 minutes.",
        "Heat a pan and brush oil all over the pan. Then turn flame into low and pour a spoonful of batter in the pan. Spread like a round shape roti. Then allow it to cook one side.",
        "When done, flip it and cook another side. Add 1 tsp of oil and cook both sides till brown in color. Then take out of the pan and keep on a tissue paper to absorb excess oil. Then serve.",
      ],
      "youtubeUrl": "https://youtu.be/WZuBGXtcXzU",
    },
    {
      "id": "02",
      "title": "Restaurant Style Garlic Bread Recipe",
      "image": "assets/images/dessert/2.jpg",
      "ingredients": [
        "1 cup Wheat flour",
        "1 tsp Dry yeast",
        "As required Warm milk or water",
        "2 tbsp Oil",
        "1 tsp Sugar",
        "To taste Salt",
        "1 tbsp Butter",
        "1 tbsp Chopped garlic",
        "2 tbsp Coriander leaves",
        "As required Grated cheese",
        "As required Chili flakes",
        "As required Italian mixed herb",
      ],
      "directions": [
        "Take a large bowl. Add flour, sugar, salt and yeast. Mix all dry ingredients. Then gradually add lukewarm liquid milk and make a soft dough. Add oil and again knead the dough for 2 to 3 minutes. Cover and leave it for 2 hours to activate yeast.",
        "Now in small mixing bowl add butter, chopped garlic & coriander leaves and mix. Then spread half of this mixture on the half of the bread. Add grated cheese and sprinkle chili flakes and oregano-parsley. Fold into half and spread remaining butter mix and sprinkle chili flakes & oregano-parsley on the top.",
        "Preheat oven with 160 degree centigrade for 10 minutes. Bake for 15-20 minutes. When it is perfectly done, take out of the oven. Cool down a bit, cut into pieces and serve warm.",
      ],
      "youtubeUrl": "https://youtu.be/xDYfL_HIjhk",
    },
    {
      "id": "03",
      "title": "Palm Cake | Taler Pua/Malpua/Teler Pitha",
      "image": "assets/images/dessert/3.jpg",
      "ingredients": [
        "1 cup Palm pulp",
        "2 cups Rice flour",
        "1/2 cup All purpose flour",
        "3/4 cup Sugar",
        "To taste Salt",
        "For deep fry Oil",
      ],
      "directions": [
        "In a bowl add palm pulp, rice flour, all purpose flour, sugar, salt and milk. Add water gradually and make a smooth batter. Whisk the batter for 2-3 minutes till smooth. Cover and rest for 30 minutes.",
        "After 30 minutes whisk the batter again with your hands or whisk for 5 minutes.",
        "Heat oil in a pan for deep fry. At first heat oil on medium flame. Then turn flame into low and pour a spoonful of batter in the oil. Then allow it to rise and puff up. You can tap oil by a spoon or spatula on the top to rise up. Then fry both sides till brown and perfectly cooked.",
        "When done, take out of the oil by a strainer and keep on a tissue paper to absorb excess oil. Then serve.",
      ],
      "youtubeUrl": "https://youtu.be/8XCiUiCe2uU",
    },
  ],
  "fast_food": [
    {
      "id": "01",
      "title": "No Dough Paratha Recipe | Bella Chara Porota",
      "image": "assets/images/fast_food/1.jpg",
      "ingredients": [
        "1 cup Wheat flour",
        "1 tbsp Milk powder",
        "1/2 tsp Sugar",
        "To taste Salt",
        "To fry Oil",
      ],
      "directions": [
        "In a bowl take all purpose flour, sugar, salt and milk powder. Add water gradually and make a smooth batter. Whisk the batter for 2-3 minutes till smooth. Cover and rest for 5 minutes.",
        "Heat a pan and brush oil all over the pan. Then turn flame into low and pour a spoonful of batter in the pan. Spread like a round shape roti. Then allow it to cook one side.",
        "When done, flip it and cook another side. Add 1 tsp of oil and cook both sides till brown in color. Then take out of the pan and keep on a tissue paper to absorb excess oil. Then serve.",
      ],
      "youtubeUrl": "https://youtu.be/WZuBGXtcXzU",
    },
    {
      "id": "02",
      "title": "Restaurant Style Garlic Bread Recipe",
      "image": "assets/images/fast_food/2.jpg",
      "ingredients": [
        "1 cup Wheat flour",
        "1 tsp Dry yeast",
        "As required Warm milk or water",
        "2 tbsp Oil",
        "1 tsp Sugar",
        "To taste Salt",
        "1 tbsp Butter",
        "1 tbsp Chopped garlic",
        "2 tbsp Coriander leaves",
        "As required Grated cheese",
        "As required Chili flakes",
        "As required Italian mixed herb",
      ],
      "directions": [
        "Take a large bowl. Add flour, sugar, salt and yeast. Mix all dry ingredients. Then gradually add lukewarm liquid milk and make a soft dough. Add oil and again knead the dough for 2 to 3 minutes. Cover and leave it for 2 hours to activate yeast.",
        "Now in small mixing bowl add butter, chopped garlic & coriander leaves and mix. Then spread half of this mixture on the half of the bread. Add grated cheese and sprinkle chili flakes and oregano-parsley. Fold into half and spread remaining butter mix and sprinkle chili flakes & oregano-parsley on the top.",
        "Preheat oven with 160 degree centigrade for 10 minutes. Bake for 15-20 minutes. When it is perfectly done, take out of the oven. Cool down a bit, cut into pieces and serve warm.",
      ],
      "youtubeUrl": "https://youtu.be/xDYfL_HIjhk",
    },
    {
      "id": "03",
      "title": "Palm Cake | Taler Pua/Malpua/Teler Pitha",
      "image": "assets/images/fast_food/3.jpg",
      "ingredients": [
        "1 cup Palm pulp",
        "2 cups Rice flour",
        "1/2 cup All purpose flour",
        "3/4 cup Sugar",
        "To taste Salt",
        "For deep fry Oil",
      ],
      "directions": [
        "In a bowl add palm pulp, rice flour, all purpose flour, sugar, salt and milk. Add water gradually and make a smooth batter. Whisk the batter for 2-3 minutes till smooth. Cover and rest for 30 minutes.",
        "After 30 minutes whisk the batter again with your hands or whisk for 5 minutes.",
        "Heat oil in a pan for deep fry. At first heat oil on medium flame. Then turn flame into low and pour a spoonful of batter in the oil. Then allow it to rise and puff up. You can tap oil by a spoon or spatula on the top to rise up. Then fry both sides till brown and perfectly cooked.",
        "When done, take out of the oil by a strainer and keep on a tissue paper to absorb excess oil. Then serve.",
      ],
      "youtubeUrl": "https://youtu.be/8XCiUiCe2uU",
    },
  ],
  "non_veg": [
    {
      "id": "01",
      "title": "No Dough Paratha Recipe | Bella Chara Porota",
      "image": "assets/images/non_veg/1.jpg",
      "ingredients": [
        "1 cup Wheat flour",
        "1 tbsp Milk powder",
        "1/2 tsp Sugar",
        "To taste Salt",
        "To fry Oil",
      ],
      "directions": [
        "In a bowl take all purpose flour, sugar, salt and milk powder. Add water gradually and make a smooth batter. Whisk the batter for 2-3 minutes till smooth. Cover and rest for 5 minutes.",
        "Heat a pan and brush oil all over the pan. Then turn flame into low and pour a spoonful of batter in the pan. Spread like a round shape roti. Then allow it to cook one side.",
        "When done, flip it and cook another side. Add 1 tsp of oil and cook both sides till brown in color. Then take out of the pan and keep on a tissue paper to absorb excess oil. Then serve.",
      ],
      "youtubeUrl": "https://youtu.be/WZuBGXtcXzU",
    },
    {
      "id": "02",
      "title": "Restaurant Style Garlic Bread Recipe",
      "image": "assets/images/non_veg/2.jpg",
      "ingredients": [
        "1 cup Wheat flour",
        "1 tsp Dry yeast",
        "As required Warm milk or water",
        "2 tbsp Oil",
        "1 tsp Sugar",
        "To taste Salt",
        "1 tbsp Butter",
        "1 tbsp Chopped garlic",
        "2 tbsp Coriander leaves",
        "As required Grated cheese",
        "As required Chili flakes",
        "As required Italian mixed herb",
      ],
      "directions": [
        "Take a large bowl. Add flour, sugar, salt and yeast. Mix all dry ingredients. Then gradually add lukewarm liquid milk and make a soft dough. Add oil and again knead the dough for 2 to 3 minutes. Cover and leave it for 2 hours to activate yeast.",
        "Now in small mixing bowl add butter, chopped garlic & coriander leaves and mix. Then spread half of this mixture on the half of the bread. Add grated cheese and sprinkle chili flakes and oregano-parsley. Fold into half and spread remaining butter mix and sprinkle chili flakes & oregano-parsley on the top.",
        "Preheat oven with 160 degree centigrade for 10 minutes. Bake for 15-20 minutes. When it is perfectly done, take out of the oven. Cool down a bit, cut into pieces and serve warm.",
      ],
      "youtubeUrl": "https://youtu.be/xDYfL_HIjhk",
    },
    {
      "id": "03",
      "title": "Palm Cake | Taler Pua/Malpua/Teler Pitha",
      "image": "assets/images/non_veg/3.jpg",
      "ingredients": [
        "1 cup Palm pulp",
        "2 cups Rice flour",
        "1/2 cup All purpose flour",
        "3/4 cup Sugar",
        "To taste Salt",
        "For deep fry Oil",
      ],
      "directions": [
        "In a bowl add palm pulp, rice flour, all purpose flour, sugar, salt and milk. Add water gradually and make a smooth batter. Whisk the batter for 2-3 minutes till smooth. Cover and rest for 30 minutes.",
        "After 30 minutes whisk the batter again with your hands or whisk for 5 minutes.",
        "Heat oil in a pan for deep fry. At first heat oil on medium flame. Then turn flame into low and pour a spoonful of batter in the oil. Then allow it to rise and puff up. You can tap oil by a spoon or spatula on the top to rise up. Then fry both sides till brown and perfectly cooked.",
        "When done, take out of the oil by a strainer and keep on a tissue paper to absorb excess oil. Then serve.",
      ],
      "youtubeUrl": "https://youtu.be/8XCiUiCe2uU",
    },
  ],
};
